resources_dict = {
    1: 'thread',
    2: 'stick',
    3: 'pelt',
    4: 'bone',
    5: 'coal',
    6: 'charcoal',
    7: 'powder',
    8: 'iron ore',
    9: 'cloth',
    10: 'silver ore',
    11: 'bauxite',
    12: 'cord',
    13: 'magic stone',
    14: 'wooden shaft',
    15: 'sapphire',
    16: 'solvent',
    17: 'ruby',
    18: 'hardener',
    19: 'steel',
    20: 'leather',
    21: 'bone powder',
    22: 'string',
    23: 'coke',
    24: 'purified powder',
    25: 'silver alloy',
    27: 'steel mold',
    28: 'silver mold',
    29: 'blacksmith frame',
    30: 'artisan frame',
    31: 'rope',
    32: 'silver frame',
    33: 'metal plate',
    34: 'metallic fiber',
    35: 'crafted leather',
    36: 'quality cloth',
    37: 'blacksmith mold',
    38: 'artisan mold',
    39: 'stinky sumac',
    40: 'mercy sassafras',
    41: 'cliff rue',
    42: 'love creeper',
    43: 'wolf root',
    44: 'swamp lavender',
    45: 'white blossom',
    46: 'ilaves',
    47: 'ephijora',
    48: 'storm hyssop',
    49: 'cave garlic',
    50: 'yellow seed',
    51: 'tecceagrass',
    52: 'spring bay leaf',
    53: 'ash rosemary',
    54: 'sanguine parsley',
    55: 'sun tarragon',
    56: 'maccunut',
    57: 'dragon seed',
    58: 'queen\'s pepper',
    59: 'plasma of abyss',
    60: 'ultramarine dust',
    61: 'ethereal bone',
    62: 'itacory',
    63: 'assassin vine',
    64: 'kloliarway',
    65: 'astrulic',
    66: 'flammia nut',
    67: 'plexisop',
    68: 'mammoth dill',
    69: 'silver dust'
}
